coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 70.49808429118774
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 134, in test6\n    'DictSet expected at most 1 arguments, got 2')\nAssertionError:\
    \ 'Dict[22 chars] arguments, got %dDictSet expected at most 1 arguments, got %d'\
    \ != 'Dict[22 chars] arguments, got 2'\n- DictSet expected at most 1 arguments,\
    \ got %dDictSet expected at most 1 arguments, got %d\n+ DictSet expected at most\
    \ 1 arguments, got 2\n\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: &id001
  mutations:
  - lineno: 66
    operator: AOR
  number: 1
  status: killed
  tests_run: 39
  time: 0.005983114242553711
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 134, in test6\n    'DictSet expected at most 1 arguments, got 2')\nAssertionError:\
    \ 'DictSet expected at most 1 arguments, got 4' != 'DictSet expected at most 1\
    \ arguments, got 2'\n- DictSet expected at most 1 arguments, got 4\n?        \
    \                                   ^\n+ DictSet expected at most 1 arguments,\
    \ got 2\n?                                           ^\n\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 66
    operator: AOR
  number: 2
  status: killed
  tests_run: 39
  time: 0.003989219665527344
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 91
    operator: AOR
  number: 3
  status: survived
  tests_run: 173
  time: 0.016950130462646484
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 91
    operator: AOR
  number: 4
  status: survived
  tests_run: 173
  time: 0.017209768295288086
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 111
    operator: AOR
  number: 5
  status: survived
  tests_run: 173
  time: 0.016101837158203125
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 116
    operator: AOR
  number: 6
  status: survived
  tests_run: 173
  time: 0.015919208526611328
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 129
    operator: AOR
  number: 7
  status: survived
  tests_run: 173
  time: 0.01608109474182129
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 106, in test2\n    \"'int' object is not iterable\")\nAssertionError: \"can't\
    \ multiply sequence by non-int of type 'str'\" != \"'int' object is not iterable\"\
    \n- can't multiply sequence by non-int of type 'str'\n+ 'int' object is not iterable\n\
    \n"
  killer: test2 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 134
    operator: AOR
  number: 8
  status: killed
  tests_run: 28
  time: 0.0029449462890625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1439, in test1\n    \"'int' object is not iterable\")\nAssertionError: \"can't\
    \ multiply sequence by non-int of type 'str'\" != \"'int' object is not iterable\"\
    \n- can't multiply sequence by non-int of type 'str'\n+ 'int' object is not iterable\n\
    \n"
  killer: test1 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 139
    operator: AOR
  number: 9
  status: killed
  tests_run: 16
  time: 0.002168416976928711
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 99, in test1\n    \"'int' object is not iterable\")\nAssertionError: \"can't\
    \ multiply sequence by non-int of type 'str'\" != \"'int' object is not iterable\"\
    \n- can't multiply sequence by non-int of type 'str'\n+ 'int' object is not iterable\n\
    \n"
  killer: test1 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 148
    operator: AOR
  number: 10
  status: killed
  tests_run: 27
  time: 0.0029556751251220703
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 638
    operator: AOR
  number: 11
  status: incompetent
  tests_run: 172
  time: 0.01806330680847168
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 639
    operator: AOR
  number: 12
  status: survived
  tests_run: 173
  time: 0.015909910202026367
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 664
    operator: AOR
  number: 13
  status: survived
  tests_run: 173
  time: 0.015911102294921875
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 687
    operator: AOR
  number: 14
  status: survived
  tests_run: 173
  time: 0.01594090461730957
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 687
    operator: AOR
  number: 15
  status: survived
  tests_run: 173
  time: 0.0160064697265625
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 687
    operator: AOR
  number: 16
  status: survived
  tests_run: 173
  time: 0.015955686569213867
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 687
    operator: AOR
  number: 17
  status: killed
  tests_run: 166
  time: 0.01796412467956543
- exception_traceback: "Traceback (most recent call last):\n  File \"dictset\", line\
    \ 695, in unique_combinations\n  File \"dictset\", line 695, in <listcomp>\nStopIteration\n\
    \nThe above exception was the direct cause of the following exception:\n\nTraceback\
    \ (most recent call last):\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in test1\n    self.assertEqual([v\
    \ for v in g], [['1', '5'],\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in <listcomp>\n\
    \    self.assertEqual([v for v in g], [['1', '5'],\nRuntimeError: generator raised\
    \ StopIteration\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 687
    operator: AOR
  number: 18
  status: killed
  tests_run: 166
  time: 0.017952919006347656
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 228
    operator: ASR
  number: 19
  status: survived
  tests_run: 173
  time: 0.015949487686157227
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 257
    operator: ASR
  number: 20
  status: survived
  tests_run: 173
  time: 0.017087697982788086
- exception_traceback: "Traceback (most recent call last):\n  File \"dictset\", line\
    \ 695, in unique_combinations\n  File \"dictset\", line 695, in <listcomp>\nStopIteration\n\
    \nThe above exception was the direct cause of the following exception:\n\nTraceback\
    \ (most recent call last):\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in test1\n    self.assertEqual([v\
    \ for v in g], [['1', '5'],\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in <listcomp>\n\
    \    self.assertEqual([v for v in g], [['1', '5'],\nRuntimeError: generator raised\
    \ StopIteration\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 686
    operator: ASR
  number: 21
  status: killed
  tests_run: 166
  time: 0.017952442169189453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 686
    operator: ASR
  number: 22
  status: killed
  tests_run: 166
  time: 0.016954898834228516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1557, in test1\n    ['2', '8']])\nAssertionError: Lists differ: [['1', '5'],\
    \ ['2', '6'], ['1', '7'], ['2', '8'], ['1', '[35 chars]'8']] != [['1', '5'], ['1',\
    \ '6'], ['1', '7'], ['1', '8'], ['2', '[35 chars]'8']]\n\nFirst differing element\
    \ 1:\n['2', '6']\n['1', '6']\n\n  [['1', '5'],\n+  ['1', '6'],\n+  ['1', '7'],\n\
    +  ['1', '8'],\n+  ['2', '5'],\n   ['2', '6'],\n-  ['1', '7'],\n?    ^\n\n+  ['2',\
    \ '7'],\n?    ^\n\n-  ['2', '8'],\n-  ['1', '5'],\n-  ['2', '6'],\n-  ['1', '7'],\n\
    \   ['2', '8']]\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 686
    operator: ASR
  number: 23
  status: killed
  tests_run: 166
  time: 0.016919612884521484
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 109
    operator: COD
  number: 24
  status: incompetent
  tests_run: 28
  time: 0.008931875228881836
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 113
    operator: COD
  number: 25
  status: incompetent
  tests_run: 28
  time: 0.007942676544189453
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 114
    operator: COD
  number: 26
  status: survived
  tests_run: 173
  time: 0.0159914493560791
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 127
    operator: COD
  number: 27
  status: killed
  tests_run: 12
  time: 0.0020318031311035156
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 127, in test5\n    \"unhashable type: 'set'\")\nAssertionError: \"'list' object\
    \ is not iterable\" != \"unhashable type: 'set'\"\n- 'list' object is not iterable\n\
    + unhashable type: 'set'\n\n"
  killer: test5 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 131
    operator: COD
  number: 28
  status: killed
  tests_run: 38
  time: 0.004177093505859375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 132
    operator: COD
  number: 29
  status: survived
  tests_run: 173
  time: 0.015958786010742188
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 145
    operator: COD
  number: 30
  status: incompetent
  tests_run: 172
  time: 0.016865015029907227
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 146
    operator: COD
  number: 31
  status: survived
  tests_run: 173
  time: 0.015775680541992188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 161, in update\nKeyError: 'a'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 159
    operator: COD
  number: 32
  status: killed
  tests_run: 1
  time: 0.0015854835510253906
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 167
    operator: COD
  number: 33
  status: killed
  tests_run: 12
  time: 0.0009987354278564453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 156, in test23\n    d2l(DictSet(a='', b='123', c='45556')),\n  File \"dictset\"\
    , line 59, in __init__\n  File \"dictset\", line 175, in update\nKeyError: 'a'\n"
  killer: test23 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 173
    operator: COD
  number: 34
  status: killed
  tests_run: 32
  time: 0.0039784908294677734
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 197
    operator: COD
  number: 35
  status: survived
  tests_run: 173
  time: 0.01770496368408203
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 266
    operator: COD
  number: 36
  status: incompetent
  tests_run: 57
  time: 0.007069826126098633
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1354, in test0\n    self.assertTrue(L <= M)\nAssertionError: False is not true\n"
  killer: test0 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 274
    operator: COD
  number: 37
  status: killed
  tests_run: 56
  time: 0.005978822708129883
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 293
    operator: COD
  number: 38
  status: incompetent
  tests_run: 16
  time: 0.004026651382446289
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 301
    operator: COD
  number: 39
  status: killed
  tests_run: 15
  time: 0.0020599365234375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 322
    operator: COD
  number: 40
  status: survived
  tests_run: 173
  time: 0.01794576644897461
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 586, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__ior__)
  module: *id001
  mutations:
  - lineno: 329
    operator: COD
  number: 41
  status: killed
  tests_run: 41
  time: 0.003988981246948242
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 353
    operator: COD
  number: 42
  status: survived
  tests_run: 173
  time: 0.016924619674682617
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1230, in test1\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [('a', []), ('c', []), ('d', [])] != []\n\nFirst list contains 3 additional\
    \ elements.\nFirst extra element 0:\n('a', [])\n\n- [('a', []), ('c', []), ('d',\
    \ [])]\n+ []\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 364
    operator: COD
  number: 43
  status: killed
  tests_run: 2
  time: 0.0009503364562988281
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 389
    operator: COD
  number: 44
  status: survived
  tests_run: 173
  time: 0.01600337028503418
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 682, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__isub__)
  module: *id001
  mutations:
  - lineno: 396
    operator: COD
  number: 45
  status: killed
  tests_run: 45
  time: 0.003978729248046875
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 422
    operator: COD
  number: 46
  status: survived
  tests_run: 173
  time: 0.019901275634765625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 778, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__ixor__)
  module: *id001
  mutations:
  - lineno: 429
    operator: COD
  number: 47
  status: killed
  tests_run: 52
  time: 0.0049860477447509766
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 452
    operator: COD
  number: 48
  status: survived
  tests_run: 173
  time: 0.015993595123291016
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 475
    operator: COD
  number: 49
  status: survived
  tests_run: 173
  time: 0.014956474304199219
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 499
    operator: COD
  number: 50
  status: survived
  tests_run: 173
  time: 0.01592087745666504
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 282, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['9'])] != [('a', ['1']), ('c', ['5', '6', '7', '8', '9'])]\n\
    \nFirst differing element 1:\n('c', ['9'])\n('c', ['5', '6', '7', '8', '9'])\n\
    \n- [('a', ['1']), ('c', ['9'])]\n+ [('a', ['1']), ('c', ['5', '6', '7', '8',\
    \ '9'])]\n"
  killer: test0 (test__dictset.TestDictSet_add)
  module: *id001
  mutations:
  - lineno: 526
    operator: COD
  number: 51
  status: killed
  tests_run: 83
  time: 0.008356571197509766
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 341, in test01\n    L.remove('c')\n  File \"dictset\", line 606, in remove\n\
    KeyError: 'c'\n"
  killer: test01 (test__dictset.TestDictSet_copy)
  module: *id001
  mutations:
  - lineno: 605
    operator: COD
  number: 52
  status: killed
  tests_run: 92
  time: 0.009927034378051758
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1512, in test1\n    self.assertEqual(L.__repr__(), R)\nAssertionError: 'DictSet([])'\
    \ != 'DictSet()'\n- DictSet([])\n?         --\n+ DictSet()\n\n"
  killer: test1 (test__dictset.TestDictSet__repr__)
  module: *id001
  mutations:
  - lineno: 637
    operator: COD
  number: 53
  status: killed
  tests_run: 73
  time: 0.006974458694458008
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 7
    operator: COI
  number: 54
  status: incompetent
  tests_run: 0
  time: 0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 674, in unique_combinations\nNameError: name 'reduce'\
    \ is not defined\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 9
    operator: COI
  number: 55
  status: killed
  tests_run: 166
  time: 0.017393112182617188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 58
    operator: COI
  number: 56
  status: killed
  tests_run: 1
  time: 0.0006265640258789062
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 61
    operator: COI
  number: 57
  status: killed
  tests_run: 1
  time: 0.0009517669677734375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 131, in test6\n    DictSet([(set('one'), [1]), ('two', [2])], {'three': [3]})\n\
    AssertionError: TypeError not raised\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 64
    operator: COI
  number: 58
  status: killed
  tests_run: 39
  time: 0.002983570098876953
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 89
    operator: COI
  number: 59
  status: incompetent
  tests_run: 1
  time: 0.001287221908569336
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: too many\
    \ values to unpack (expected 2)\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 95
    operator: COI
  number: 60
  status: killed
  tests_run: 36
  time: 0.0050046443939208984
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: too many\
    \ values to unpack (expected 2)\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 100
    operator: COI
  number: 61
  status: killed
  tests_run: 36
  time: 0.004640340805053711
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 104
    operator: COI
  number: 62
  status: incompetent
  tests_run: 1
  time: 0.0009877681732177734
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 107
    operator: COI
  number: 63
  status: incompetent
  tests_run: 4
  time: 0.0032224655151367188
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 109
    operator: COI
  number: 64
  status: incompetent
  tests_run: 28
  time: 0.006961822509765625
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 113
    operator: COI
  number: 65
  status: incompetent
  tests_run: 28
  time: 0.007116794586181641
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 114
    operator: COI
  number: 66
  status: survived
  tests_run: 173
  time: 0.016445636749267578
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 127
    operator: COI
  number: 67
  status: killed
  tests_run: 12
  time: 0.0009982585906982422
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 127, in test5\n    \"unhashable type: 'set'\")\nAssertionError: \"'list' object\
    \ is not iterable\" != \"unhashable type: 'set'\"\n- 'list' object is not iterable\n\
    + unhashable type: 'set'\n\n"
  killer: test5 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 131
    operator: COI
  number: 68
  status: killed
  tests_run: 38
  time: 0.0030374526977539062
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 132
    operator: COI
  number: 69
  status: survived
  tests_run: 173
  time: 0.016006946563720703
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 145
    operator: COI
  number: 70
  status: incompetent
  tests_run: 172
  time: 0.01702737808227539
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 146
    operator: COI
  number: 71
  status: survived
  tests_run: 173
  time: 0.016072988510131836
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 153
    operator: COI
  number: 72
  status: killed
  tests_run: 1
  time: 0.0010063648223876953
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: not enough\
    \ values to unpack (expected 2, got 1)\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 157
    operator: COI
  number: 73
  status: killed
  tests_run: 1
  time: 0.0029861927032470703
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 161, in update\nKeyError: 'a'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 159
    operator: COI
  number: 74
  status: killed
  tests_run: 1
  time: 0.0019850730895996094
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 161, in update\nKeyError: 'a'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 159
    operator: COI
  number: 75
  status: killed
  tests_run: 1
  time: 0.002276182174682617
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 167
    operator: COI
  number: 76
  status: killed
  tests_run: 12
  time: 0.0019855499267578125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 167
    operator: COI
  number: 77
  status: killed
  tests_run: 12
  time: 0.001988649368286133
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 156, in test23\n    d2l(DictSet(a='', b='123', c='45556')),\n  File \"dictset\"\
    , line 59, in __init__\n  File \"dictset\", line 175, in update\nKeyError: 'a'\n"
  killer: test23 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 173
    operator: COI
  number: 78
  status: killed
  tests_run: 32
  time: 0.003977775573730469
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 156, in test23\n    d2l(DictSet(a='', b='123', c='45556')),\n  File \"dictset\"\
    , line 59, in __init__\n  File \"dictset\", line 175, in update\nKeyError: 'a'\n"
  killer: test23 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 173
    operator: COI
  number: 79
  status: killed
  tests_run: 32
  time: 0.004940509796142578
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 197
    operator: COI
  number: 80
  status: survived
  tests_run: 173
  time: 0.01594710350036621
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 219
    operator: COI
  number: 81
  status: killed
  tests_run: 12
  time: 0.0009870529174804688
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 248
    operator: COI
  number: 82
  status: killed
  tests_run: 65
  time: 0.0059735774993896484
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 266
    operator: COI
  number: 83
  status: incompetent
  tests_run: 57
  time: 0.0072019100189208984
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1371, in test31\n    self.assertFalse(L <= M)\nAssertionError: True is not false\n"
  killer: test31 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 269
    operator: COI
  number: 84
  status: killed
  tests_run: 59
  time: 0.005446910858154297
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1354, in test0\n    self.assertTrue(L <= M)\nAssertionError: False is not true\n"
  killer: test0 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 274
    operator: COI
  number: 85
  status: killed
  tests_run: 56
  time: 0.0059375762939453125
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 293
    operator: COI
  number: 86
  status: incompetent
  tests_run: 16
  time: 0.0029463768005371094
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 296
    operator: COI
  number: 87
  status: killed
  tests_run: 15
  time: 0.0019855499267578125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 301
    operator: COI
  number: 88
  status: killed
  tests_run: 15
  time: 0.0019462108612060547
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 322
    operator: COI
  number: 89
  status: survived
  tests_run: 173
  time: 0.01695871353149414
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 586, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__ior__)
  module: *id001
  mutations:
  - lineno: 329
    operator: COI
  number: 90
  status: killed
  tests_run: 41
  time: 0.003988504409790039
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 353
    operator: COI
  number: 91
  status: survived
  tests_run: 173
  time: 0.016082286834716797
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1240, in test2\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [] != [('a', ['1']), ('c', ['5', '7', '8'])]\n\nSecond list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n+ [('a', ['1']), ('c',\
    \ ['5', '7', '8'])]\n"
  killer: test2 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 357
    operator: COI
  number: 92
  status: killed
  tests_run: 3
  time: 0.0006618499755859375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1230, in test1\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [('a', []), ('c', []), ('d', [])] != []\n\nFirst list contains 3 additional\
    \ elements.\nFirst extra element 0:\n('a', [])\n\n- [('a', []), ('c', []), ('d',\
    \ [])]\n+ []\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 364
    operator: COI
  number: 93
  status: killed
  tests_run: 2
  time: 0.0009508132934570312
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 389
    operator: COI
  number: 94
  status: survived
  tests_run: 173
  time: 0.016462087631225586
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 682, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__isub__)
  module: *id001
  mutations:
  - lineno: 396
    operator: COI
  number: 95
  status: killed
  tests_run: 45
  time: 0.0034079551696777344
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 422
    operator: COI
  number: 96
  status: survived
  tests_run: 173
  time: 0.015943288803100586
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 778, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__ixor__)
  module: *id001
  mutations:
  - lineno: 429
    operator: COI
  number: 97
  status: killed
  tests_run: 52
  time: 0.00498652458190918
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 452
    operator: COI
  number: 98
  status: survived
  tests_run: 173
  time: 0.01595616340637207
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 826, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('a', []), ('c', [])] != []\n\nFirst list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', [])\n\n- [('a', []), ('c', [])]\n+\
    \ []\n"
  killer: test0 (test__dictset.TestDictSet_intersection_update)
  module: *id001
  mutations:
  - lineno: 458
    operator: COI
  number: 99
  status: killed
  tests_run: 124
  time: 0.015915870666503906
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 475
    operator: COI
  number: 100
  status: survived
  tests_run: 173
  time: 0.01595163345336914
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 634, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet_difference_update)
  module: *id001
  mutations:
  - lineno: 481
    operator: COI
  number: 101
  status: killed
  tests_run: 100
  time: 0.00997304916381836
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 499
    operator: COI
  number: 102
  status: survived
  tests_run: 173
  time: 0.01595783233642578
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 730, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet_symmetric_difference_update)
  module: *id001
  mutations:
  - lineno: 505
    operator: COI
  number: 103
  status: killed
  tests_run: 157
  time: 0.015202522277832031
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 282, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['9'])] != [('a', ['1']), ('c', ['5', '6', '7', '8', '9'])]\n\
    \nFirst differing element 1:\n('c', ['9'])\n('c', ['5', '6', '7', '8', '9'])\n\
    \n- [('a', ['1']), ('c', ['9'])]\n+ [('a', ['1']), ('c', ['5', '6', '7', '8',\
    \ '9'])]\n"
  killer: test0 (test__dictset.TestDictSet_add)
  module: *id001
  mutations:
  - lineno: 526
    operator: COI
  number: 104
  status: killed
  tests_run: 83
  time: 0.008966207504272461
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 282, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['5', '6', '7', '8'])] != [('a', ['1']), ('c', ['5', '6',\
    \ '7', '8', '9'])]\n\nFirst differing element 1:\n('c', ['5', '6', '7', '8'])\n\
    ('c', ['5', '6', '7', '8', '9'])\n\n- [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8', '9'])]\n?                        \
    \                +++++\n\n"
  killer: test0 (test__dictset.TestDictSet_add)
  module: *id001
  mutations:
  - lineno: 529
    operator: COI
  number: 105
  status: killed
  tests_run: 83
  time: 0.00897669792175293
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 534
    operator: COI
  number: 106
  status: survived
  tests_run: 173
  time: 0.016845226287841797
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1219, in test0\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 357, in intersection\n  File\
    \ \"dictset\", line 228, in __eq__\n  File \"dictset\", line 567, in get\nKeyError:\
    \ 'e'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 549
    operator: COI
  number: 107
  status: killed
  tests_run: 1
  time: 0.0039746761322021484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 558
    operator: COI
  number: 108
  status: killed
  tests_run: 15
  time: 0.0020296573638916016
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1219, in test0\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 357, in intersection\n  File\
    \ \"dictset\", line 228, in __eq__\n  File \"dictset\", line 567, in get\nKeyError:\
    \ 'e'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 566
    operator: COI
  number: 109
  status: killed
  tests_run: 1
  time: 0.003986358642578125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1219, in test0\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 357, in intersection\n  File\
    \ \"dictset\", line 228, in __eq__\n  File \"dictset\", line 567, in get\nKeyError:\
    \ 'e'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 566
    operator: COI
  number: 110
  status: killed
  tests_run: 1
  time: 0.003678560256958008
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 568
    operator: COI
  number: 111
  status: incompetent
  tests_run: 78
  time: 0.009971857070922852
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1229, in test1\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 362, in intersection\n  File\
    \ \"dictset\", line 582, in setdefault\nKeyError: 'd'\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 581
    operator: COI
  number: 112
  status: killed
  tests_run: 2
  time: 0.002939462661743164
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1229, in test1\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 362, in intersection\n  File\
    \ \"dictset\", line 582, in setdefault\nKeyError: 'd'\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 581
    operator: COI
  number: 113
  status: killed
  tests_run: 2
  time: 0.002299070358276367
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1229, in test1\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 363, in intersection\nKeyError:\
    \ 'd'\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 584
    operator: COI
  number: 114
  status: killed
  tests_run: 2
  time: 0.0016791820526123047
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 341, in test01\n    L.remove('c')\n  File \"dictset\", line 606, in remove\n\
    KeyError: 'c'\n"
  killer: test01 (test__dictset.TestDictSet_copy)
  module: *id001
  mutations:
  - lineno: 605
    operator: COI
  number: 115
  status: killed
  tests_run: 92
  time: 0.009874343872070312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 341, in test01\n    L.remove('c')\n  File \"dictset\", line 609, in remove\n\
    KeyError: None\n"
  killer: test01 (test__dictset.TestDictSet_copy)
  module: *id001
  mutations:
  - lineno: 608
    operator: COI
  number: 116
  status: killed
  tests_run: 92
  time: 0.010106325149536133
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 389, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1'])] != [('a', ['1']), ('c', ['5', '6', '7'])]\n\nSecond list contains\
    \ 1 additional elements.\nFirst extra element 1:\n('c', ['5', '6', '7'])\n\n-\
    \ [('a', ['1'])]\n+ [('a', ['1']), ('c', ['5', '6', '7'])]\n"
  killer: test0 (test__dictset.TestDictSet_discard)
  module: *id001
  mutations:
  - lineno: 622
    operator: COI
  number: 117
  status: killed
  tests_run: 104
  time: 0.010969161987304688
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1512, in test1\n    self.assertEqual(L.__repr__(), R)\nAssertionError: 'DictSet([])'\
    \ != 'DictSet()'\n- DictSet([])\n?         --\n+ DictSet()\n\n"
  killer: test1 (test__dictset.TestDictSet__repr__)
  module: *id001
  mutations:
  - lineno: 637
    operator: COI
  number: 118
  status: killed
  tests_run: 73
  time: 0.006956338882446289
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1544, in test0\n    self.assertEqual([v for v in g], [None])\nAssertionError:\
    \ Lists differ: [['1', '5'], ['1', '6'], ['1', '7'], ['1', '8']] != [None]\n\n\
    First differing element 0:\n['1', '5']\nNone\n\nFirst list contains 3 additional\
    \ elements.\nFirst extra element 1:\n['1', '6']\n\n- [['1', '5'], ['1', '6'],\
    \ ['1', '7'], ['1', '8']]\n+ [None]\n"
  killer: test0 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 657
    operator: COI
  number: 119
  status: killed
  tests_run: 165
  time: 0.017011642456054688
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 662
    operator: COI
  number: 120
  status: killed
  tests_run: 166
  time: 0.01603841781616211
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 668
    operator: COI
  number: 121
  status: incompetent
  tests_run: 165
  time: 0.018062591552734375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 685
    operator: COI
  number: 122
  status: killed
  tests_run: 166
  time: 0.017964601516723633
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 706
    operator: COI
  number: 123
  status: incompetent
  tests_run: 113
  time: 0.011970758438110352
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 7
    operator: CRP
  number: 124
  status: survived
  tests_run: 173
  time: 0.017940521240234375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 7
    operator: CRP
  number: 125
  status: incompetent
  tests_run: 0
  time: 0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 674, in unique_combinations\nNameError: name 'reduce'\
    \ is not defined\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 9
    operator: CRP
  number: 126
  status: killed
  tests_run: 166
  time: 0.01793503761291504
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 674, in unique_combinations\nNameError: name 'reduce'\
    \ is not defined\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 9
    operator: CRP
  number: 127
  status: killed
  tests_run: 166
  time: 0.018939495086669922
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 58
    operator: CRP
  number: 128
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1219, in test0\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 358, in intersection\n  File\
    \ \"dictset\", line 59, in __init__\nIndexError: tuple index out of range\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 59
    operator: CRP
  number: 129
  status: killed
  tests_run: 1
  time: 0.0029900074005126953
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 61
    operator: CRP
  number: 130
  status: killed
  tests_run: 1
  time: 0.0009551048278808594
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 62
    operator: CRP
  number: 131
  status: killed
  tests_run: 1
  time: 0.0009508132934570312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\nIndexError: tuple index out of range\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 62
    operator: CRP
  number: 132
  status: killed
  tests_run: 1
  time: 0.0009970664978027344
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 131, in test6\n    DictSet([(set('one'), [1]), ('two', [2])], {'three': [3]})\n\
    AssertionError: TypeError not raised\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 64
    operator: CRP
  number: 133
  status: killed
  tests_run: 39
  time: 0.00397944450378418
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 134, in test6\n    'DictSet expected at most 1 arguments, got 2')\nAssertionError:\
    \ 'not all arguments converted during string formatting' != 'DictSet expected\
    \ at most 1 arguments, got 2'\n- not all arguments converted during string formatting\n\
    + DictSet expected at most 1 arguments, got 2\n\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 66
    operator: CRP
  number: 134
  status: killed
  tests_run: 39
  time: 0.0059888362884521484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 134, in test6\n    'DictSet expected at most 1 arguments, got 2')\nAssertionError:\
    \ 'not all arguments converted during string formatting' != 'DictSet expected\
    \ at most 1 arguments, got 2'\n- not all arguments converted during string formatting\n\
    + DictSet expected at most 1 arguments, got 2\n\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 66
    operator: CRP
  number: 135
  status: killed
  tests_run: 39
  time: 0.003941059112548828
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 134, in test6\n    'DictSet expected at most 1 arguments, got 2')\nAssertionError:\
    \ 'DictSet expected at most 1 arguments, got 1' != 'DictSet expected at most 1\
    \ arguments, got 2'\n- DictSet expected at most 1 arguments, got 1\n?        \
    \                                   ^\n+ DictSet expected at most 1 arguments,\
    \ got 2\n?                                           ^\n\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 66
    operator: CRP
  number: 136
  status: killed
  tests_run: 39
  time: 0.003973722457885742
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 89
    operator: CRP
  number: 137
  status: survived
  tests_run: 173
  time: 0.01794600486755371
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 91
    operator: CRP
  number: 138
  status: survived
  tests_run: 173
  time: 0.01763153076171875
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 91
    operator: CRP
  number: 139
  status: survived
  tests_run: 173
  time: 0.017942428588867188
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 91
    operator: CRP
  number: 140
  status: survived
  tests_run: 173
  time: 0.01927351951599121
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: too many\
    \ values to unpack (expected 2)\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 95
    operator: CRP
  number: 141
  status: killed
  tests_run: 36
  time: 0.004307270050048828
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 96, in update\nIndexError: tuple index\
    \ out of range\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 96
    operator: CRP
  number: 142
  status: killed
  tests_run: 1
  time: 0.0018923282623291016
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 104
    operator: CRP
  number: 143
  status: incompetent
  tests_run: 1
  time: 0.0009875297546386719
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 104
    operator: CRP
  number: 144
  status: incompetent
  tests_run: 1
  time: 0.0009989738464355469
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 107
    operator: CRP
  number: 145
  status: incompetent
  tests_run: 28
  time: 0.00992584228515625
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 107
    operator: CRP
  number: 146
  status: incompetent
  tests_run: 28
  time: 0.00693202018737793
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 109
    operator: CRP
  number: 147
  status: incompetent
  tests_run: 28
  time: 0.00693511962890625
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 109
    operator: CRP
  number: 148
  status: incompetent
  tests_run: 28
  time: 0.00796651840209961
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 111
    operator: CRP
  number: 149
  status: survived
  tests_run: 173
  time: 0.015949726104736328
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 111
    operator: CRP
  number: 150
  status: survived
  tests_run: 173
  time: 0.01603221893310547
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 113
    operator: CRP
  number: 151
  status: incompetent
  tests_run: 28
  time: 0.007077217102050781
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 113
    operator: CRP
  number: 152
  status: incompetent
  tests_run: 28
  time: 0.007976770401000977
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 116
    operator: CRP
  number: 153
  status: survived
  tests_run: 173
  time: 0.01595759391784668
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 116
    operator: CRP
  number: 154
  status: survived
  tests_run: 173
  time: 0.016099929809570312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 113, in test3\n    'could not unpack arg to key/value pairs')\nAssertionError:\
    \ 'mutpy' != 'could not unpack arg to key/value pairs'\n- mutpy\n+ could not unpack\
    \ arg to key/value pairs\n\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 125
    operator: CRP
  number: 155
  status: killed
  tests_run: 36
  time: 0.004030466079711914
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 113, in test3\n    'could not unpack arg to key/value pairs')\nAssertionError:\
    \ '' != 'could not unpack arg to key/value pairs'\n+ could not unpack arg to key/value\
    \ pairs\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 125
    operator: CRP
  number: 156
  status: killed
  tests_run: 36
  time: 0.004029989242553711
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 127
    operator: CRP
  number: 157
  status: killed
  tests_run: 12
  time: 0.0019915103912353516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 127
    operator: CRP
  number: 158
  status: killed
  tests_run: 12
  time: 0.002961397171020508
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 129
    operator: CRP
  number: 159
  status: survived
  tests_run: 173
  time: 0.020943880081176758
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 129
    operator: CRP
  number: 160
  status: survived
  tests_run: 173
  time: 0.017545700073242188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 127, in test5\n    \"unhashable type: 'set'\")\nAssertionError: \"'list' object\
    \ is not iterable\" != \"unhashable type: 'set'\"\n- 'list' object is not iterable\n\
    + unhashable type: 'set'\n\n"
  killer: test5 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 131
    operator: CRP
  number: 161
  status: killed
  tests_run: 38
  time: 0.003954648971557617
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 127, in test5\n    \"unhashable type: 'set'\")\nAssertionError: \"'list' object\
    \ is not iterable\" != \"unhashable type: 'set'\"\n- 'list' object is not iterable\n\
    + unhashable type: 'set'\n\n"
  killer: test5 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 131
    operator: CRP
  number: 162
  status: killed
  tests_run: 38
  time: 0.004094362258911133
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 106, in test2\n    \"'int' object is not iterable\")\nAssertionError: 'not all\
    \ arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test2 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 134
    operator: CRP
  number: 163
  status: killed
  tests_run: 28
  time: 0.0029981136322021484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 106, in test2\n    \"'int' object is not iterable\")\nAssertionError: 'not all\
    \ arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test2 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 134
    operator: CRP
  number: 164
  status: killed
  tests_run: 28
  time: 0.003027200698852539
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1439, in test1\n    \"'int' object is not iterable\")\nAssertionError: 'not\
    \ all arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test1 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 139
    operator: CRP
  number: 165
  status: killed
  tests_run: 16
  time: 0.002028226852416992
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1439, in test1\n    \"'int' object is not iterable\")\nAssertionError: 'not\
    \ all arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test1 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 139
    operator: CRP
  number: 166
  status: killed
  tests_run: 16
  time: 0.0020334720611572266
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 145
    operator: CRP
  number: 167
  status: incompetent
  tests_run: 172
  time: 0.01894974708557129
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 145
    operator: CRP
  number: 168
  status: incompetent
  tests_run: 172
  time: 0.01595783233642578
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 99, in test1\n    \"'int' object is not iterable\")\nAssertionError: 'not all\
    \ arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test1 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 148
    operator: CRP
  number: 169
  status: killed
  tests_run: 27
  time: 0.0030260086059570312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 99, in test1\n    \"'int' object is not iterable\")\nAssertionError: 'not all\
    \ arguments converted during string formatting' != \"'int' object is not iterable\"\
    \n- not all arguments converted during string formatting\n+ 'int' object is not\
    \ iterable\n\n"
  killer: test1 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 148
    operator: CRP
  number: 170
  status: killed
  tests_run: 27
  time: 0.0030312538146972656
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 153
    operator: CRP
  number: 171
  status: killed
  tests_run: 1
  time: 0.000997781753540039
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 154, in update\nIndexError: tuple\
    \ index out of range\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 154
    operator: CRP
  number: 172
  status: killed
  tests_run: 1
  time: 0.0018389225006103516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: not enough\
    \ values to unpack (expected 2, got 1)\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 157
    operator: CRP
  number: 173
  status: killed
  tests_run: 1
  time: 0.0019483566284179688
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: not enough\
    \ values to unpack (expected 2, got 1)\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 157
    operator: CRP
  number: 174
  status: killed
  tests_run: 1
  time: 0.0022268295288085938
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 161, in update\nKeyError: 'a'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 159
    operator: CRP
  number: 175
  status: killed
  tests_run: 1
  time: 0.001626729965209961
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 161, in update\nKeyError: 'a'\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 160
    operator: CRP
  number: 176
  status: killed
  tests_run: 1
  time: 0.0019850730895996094
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 161
    operator: CRP
  number: 177
  status: incompetent
  tests_run: 28
  time: 0.007836341857910156
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 167
    operator: CRP
  number: 178
  status: killed
  tests_run: 12
  time: 0.001947164535522461
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 168
    operator: CRP
  number: 179
  status: killed
  tests_run: 12
  time: 0.001983165740966797
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 169
    operator: CRP
  number: 180
  status: killed
  tests_run: 12
  time: 0.0019845962524414062
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 181, in test99\n    self.assertEqual(d2l(L), s2l('a1b23c4'))\nAssertionError:\
    \ Lists differ: [('a', ['1']), ('b', ['3']), ('c', ['4'])] != [('a', ['1']), ('b',\
    \ ['2', '3']), ('c', ['4'])]\n\nFirst differing element 1:\n('b', ['3'])\n('b',\
    \ ['2', '3'])\n\n- [('a', ['1']), ('b', ['3']), ('c', ['4'])]\n+ [('a', ['1']),\
    \ ('b', ['2', '3']), ('c', ['4'])]\n?                       +++++\n\n"
  killer: test99 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 173
    operator: CRP
  number: 181
  status: killed
  tests_run: 40
  time: 0.0039408206939697266
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 156, in test23\n    d2l(DictSet(a='', b='123', c='45556')),\n  File \"dictset\"\
    , line 59, in __init__\n  File \"dictset\", line 175, in update\nKeyError: 'a'\n"
  killer: test23 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 174
    operator: CRP
  number: 182
  status: killed
  tests_run: 32
  time: 0.0039408206939697266
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 156, in test23\n    d2l(DictSet(a='', b='123', c='45556')),\n  File \"dictset\"\
    , line 59, in __init__\n  File \"dictset\", line 175, in update\nKeyError: 'a'\n"
  killer: test23 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 175
    operator: CRP
  number: 183
  status: killed
  tests_run: 32
  time: 0.0049817562103271484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 219
    operator: CRP
  number: 184
  status: killed
  tests_run: 12
  time: 0.0009920597076416016
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 220
    operator: CRP
  number: 185
  status: killed
  tests_run: 12
  time: 0.0019502639770507812
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 220
    operator: CRP
  number: 186
  status: survived
  tests_run: 173
  time: 0.01590752601623535
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 226
    operator: CRP
  number: 187
  status: killed
  tests_run: 12
  time: 0.0019860267639160156
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 229
    operator: CRP
  number: 188
  status: killed
  tests_run: 12
  time: 0.001995563507080078
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 248
    operator: CRP
  number: 189
  status: killed
  tests_run: 65
  time: 0.005936861038208008
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 249
    operator: CRP
  number: 190
  status: killed
  tests_run: 65
  time: 0.005937337875366211
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 249
    operator: CRP
  number: 191
  status: survived
  tests_run: 173
  time: 0.016945838928222656
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 255
    operator: CRP
  number: 192
  status: killed
  tests_run: 65
  time: 0.0060198307037353516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 258
    operator: CRP
  number: 193
  status: killed
  tests_run: 65
  time: 0.006944179534912109
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 826, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('a', []), ('c', [])] != []\n\nFirst list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', [])\n\n- [('a', []), ('c', [])]\n+\
    \ []\n"
  killer: test0 (test__dictset.TestDictSet_intersection_update)
  module: *id001
  mutations:
  - lineno: 458
    operator: CRP
  number: 194
  status: killed
  tests_run: 124
  time: 0.012992382049560547
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 634, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('c', ['5', '6', '7', '8'])] != [('a', ['1']), ('c', ['5', '6',\
    \ '7', '8'])]\n\nFirst differing element 0:\n('c', ['5', '6', '7', '8'])\n('a',\
    \ ['1'])\n\nSecond list contains 1 additional elements.\nFirst extra element 1:\n\
    ('c', ['5', '6', '7', '8'])\n\n- [('c', ['5', '6', '7', '8'])]\n+ [('a', ['1']),\
    \ ('c', ['5', '6', '7', '8'])]\n?  ++++++++++++++\n\n"
  killer: test0 (test__dictset.TestDictSet_difference_update)
  module: *id001
  mutations:
  - lineno: 481
    operator: CRP
  number: 195
  status: killed
  tests_run: 100
  time: 0.012967348098754883
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 730, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('c', ['5', '6', '7', '8'])] != [('a', ['1']), ('c', ['5', '6',\
    \ '7', '8'])]\n\nFirst differing element 0:\n('c', ['5', '6', '7', '8'])\n('a',\
    \ ['1'])\n\nSecond list contains 1 additional elements.\nFirst extra element 1:\n\
    ('c', ['5', '6', '7', '8'])\n\n- [('c', ['5', '6', '7', '8'])]\n+ [('a', ['1']),\
    \ ('c', ['5', '6', '7', '8'])]\n?  ++++++++++++++\n\n"
  killer: test0 (test__dictset.TestDictSet_symmetric_difference_update)
  module: *id001
  mutations:
  - lineno: 505
    operator: CRP
  number: 196
  status: killed
  tests_run: 157
  time: 0.014958620071411133
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1240, in test2\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [('c', ['5', '7', '8'])] != [('a', ['1']), ('c', ['5', '7', '8'])]\n\nFirst\
    \ differing element 0:\n('c', ['5', '7', '8'])\n('a', ['1'])\n\nSecond list contains\
    \ 1 additional elements.\nFirst extra element 1:\n('c', ['5', '7', '8'])\n\n-\
    \ [('c', ['5', '7', '8'])]\n+ [('a', ['1']), ('c', ['5', '7', '8'])]\n?  ++++++++++++++\n\
    \n"
  killer: test2 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 549
    operator: CRP
  number: 197
  status: killed
  tests_run: 3
  time: 0.0009982585906982422
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1444, in test3\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test3 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 558
    operator: CRP
  number: 198
  status: killed
  tests_run: 17
  time: 0.0014469623565673828
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 638
    operator: CRP
  number: 199
  status: incompetent
  tests_run: 172
  time: 0.01790761947631836
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 638
    operator: CRP
  number: 200
  status: incompetent
  tests_run: 172
  time: 0.018911123275756836
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 639
    operator: CRP
  number: 201
  status: survived
  tests_run: 173
  time: 0.01997542381286621
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 639
    operator: CRP
  number: 202
  status: survived
  tests_run: 173
  time: 0.0189363956451416
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 664
    operator: CRP
  number: 203
  status: survived
  tests_run: 173
  time: 0.019902706146240234
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 664
    operator: CRP
  number: 204
  status: survived
  tests_run: 173
  time: 0.02189469337463379
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 668
    operator: CRP
  number: 205
  status: incompetent
  tests_run: 172
  time: 0.017958402633666992
- exception_traceback: "Traceback (most recent call last):\n  File \"dictset\", line\
    \ 695, in unique_combinations\n  File \"dictset\", line 695, in <listcomp>\nStopIteration\n\
    \nThe above exception was the direct cause of the following exception:\n\nTraceback\
    \ (most recent call last):\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in test1\n    self.assertEqual([v\
    \ for v in g], [['1', '5'],\n  File \"C:\\Users\\steph\\Desktop\\Thesis\\Feature\
    \ Scripts\\Working\\src\\tests\\test__dictset.py\", line 1550, in <listcomp>\n\
    \    self.assertEqual([v for v in g], [['1', '5'],\nRuntimeError: generator raised\
    \ StopIteration\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 681
    operator: CRP
  number: 206
  status: killed
  tests_run: 166
  time: 0.020905733108520508
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 682
    operator: CRP
  number: 207
  status: survived
  tests_run: 173
  time: 0.0168001651763916
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 683
    operator: CRP
  number: 208
  status: survived
  tests_run: 173
  time: 0.017079591751098633
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 685
    operator: CRP
  number: 209
  status: killed
  tests_run: 166
  time: 0.017112016677856445
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 697
    operator: DDL
  number: 210
  status: incompetent
  tests_run: 113
  time: 0.011925935745239258
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 213
    operator: EHD
  number: 211
  status: incompetent
  tests_run: 172
  time: 0.01798725128173828
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 242
    operator: EHD
  number: 212
  status: incompetent
  tests_run: 172
  time: 0.017915010452270508
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 406, in test2\n    L.discard('d', '8')  # doesn't raise KeyError\n  File \"\
    dictset\", line 624, in discard\nKeyError: 'd'\n"
  killer: test2 (test__dictset.TestDictSet_discard)
  module: *id001
  mutations:
  - lineno: 625
    operator: EHD
  number: 213
  status: killed
  tests_run: 107
  time: 0.013005256652832031
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 436, in test7\n    L.discard('a')  # Shouldn't complain\n  File \"dictset\"\
    , line 629, in discard\nKeyError: 'a'\n"
  killer: test7 (test__dictset.TestDictSet_discard)
  module: *id001
  mutations:
  - lineno: 630
    operator: EHD
  number: 214
  status: killed
  tests_run: 112
  time: 0.012920379638671875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 127, in update\nUnboundLocalError:\
    \ local variable 'k' referenced before assignment\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 123
    operator: EXS
  number: 215
  status: killed
  tests_run: 36
  time: 0.00598454475402832
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1266, in test1\n    self.assertFalse(L.__eq__(M))\n  File \"dictset\", line\
    \ 220, in __eq__\nAttributeError: 'int' object has no attribute 'items'\n"
  killer: test1 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 213
    operator: EXS
  number: 216
  status: killed
  tests_run: 11
  time: 0.0029871463775634766
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1293, in test1\n    self.assertTrue(L.__ne__(M))\n  File \"dictset\", line 249,\
    \ in __ne__\nAttributeError: 'int' object has no attribute 'items'\n"
  killer: test1 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 242
    operator: EXS
  number: 217
  status: killed
  tests_run: 64
  time: 0.006935596466064453
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 539
    operator: EXS
  number: 218
  status: survived
  tests_run: 173
  time: 0.015956878662109375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 573
    operator: EXS
  number: 219
  status: survived
  tests_run: 173
  time: 0.01658034324645996
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 589
    operator: EXS
  number: 220
  status: survived
  tests_run: 173
  time: 0.016911029815673828
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 663
    operator: EXS
  number: 221
  status: survived
  tests_run: 173
  time: 0.019954919815063477
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [('a', ['1']), ('c', ['5', '6', '6', '6', '7', '8', '8'])] !=\
    \ [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nFirst differing element 1:\n\
    ('c', ['5', '6', '6', '6', '7', '8', '8'])\n('c', ['5', '6', '7', '8'])\n\n- [('a',\
    \ ['1']), ('c', ['5', '6', '6', '6', '7', '8', '8'])]\n?                     \
    \            ----------    -----\n\n+ [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 37
    operator: IOD
  number: 222
  status: killed
  tests_run: 1
  time: 0.0009946823120117188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [('a', ['1']), ('c', ['5', '6', '6', '6', '7', '8', '8'])] !=\
    \ [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nFirst differing element 1:\n\
    ('c', ['5', '6', '6', '6', '7', '8', '8'])\n('c', ['5', '6', '7', '8'])\n\n- [('a',\
    \ ['1']), ('c', ['5', '6', '6', '6', '7', '8', '8'])]\n?                     \
    \            ----------    -----\n\n+ [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 68
    operator: IOD
  number: 223
  status: killed
  tests_run: 1
  time: 0.001995563507080078
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1261, in test0\n    self.assertFalse(L.__eq__(M))\nAssertionError: NotImplemented\
    \ is not false\n"
  killer: test0 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 202
    operator: IOD
  number: 224
  status: killed
  tests_run: 10
  time: 0.0019969940185546875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: NotImplemented\
    \ is not false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 231
    operator: IOD
  number: 225
  status: killed
  tests_run: 65
  time: 0.006109476089477539
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 279
    operator: IOD
  number: 226
  status: incompetent
  tests_run: 168
  time: 0.016946077346801758
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 306
    operator: IOD
  number: 227
  status: incompetent
  tests_run: 168
  time: 0.01594686508178711
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 532
    operator: IOD
  number: 228
  status: survived
  tests_run: 173
  time: 0.01599407196044922
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 542
    operator: IOD
  number: 229
  status: incompetent
  tests_run: 7
  time: 0.0020341873168945312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1528, in test1\n    self.assertEqual(set([v for v in g]) ^ set('abc'), set())\n\
    AssertionError: Items in the first set but not the second:\n'd'\n"
  killer: test1 (test__dictset.TestDictSet__iter__)
  module: *id001
  mutations:
  - lineno: 551
    operator: IOD
  number: 230
  status: killed
  tests_run: 50
  time: 0.00496673583984375
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 561
    operator: IOD
  number: 231
  status: incompetent
  tests_run: 109
  time: 0.013962984085083008
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1229, in test1\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 363, in intersection\nAttributeError:\
    \ 'list' object has no attribute 'intersection_update'\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 576
    operator: IOD
  number: 232
  status: killed
  tests_run: 2
  time: 0.002956390380859375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 334, in test0\n    M.add('d', '9')\nAttributeError: 'dict' object has no attribute\
    \ 'add'\n"
  killer: test0 (test__dictset.TestDictSet_copy)
  module: *id001
  mutations:
  - lineno: 593
    operator: IOD
  number: 233
  status: killed
  tests_run: 91
  time: 0.009904623031616211
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1512, in test1\n    self.assertEqual(L.__repr__(), R)\nAssertionError: '{}'\
    \ != 'DictSet()'\n- {}\n+ DictSet()\n\n"
  killer: test1 (test__dictset.TestDictSet__repr__)
  module: *id001
  mutations:
  - lineno: 635
    operator: IOD
  number: 234
  status: killed
  tests_run: 73
  time: 0.006982088088989258
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 697
    operator: IOD
  number: 235
  status: incompetent
  tests_run: 172
  time: 0.017257213592529297
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 562, in test2\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('a', ['1']), ('b', ['2', '3', '4']), ('c', ['5', '6', '7', '8'])]\
    \ != [('a', ['1', '2', '3']), ('b', ['2', '3', '4']), ('c', ['5', '6', '7', '8'])]\n\
    \nFirst differing element 0:\n('a', ['1'])\n('a', ['1', '2', '3'])\n\n- [('a',\
    \ ['1']), ('b', ['2', '3', '4']), ('c', ['5', '6', '7', '8'])]\n+ [('a', ['1',\
    \ '2', '3']), ('b', ['2', '3', '4']), ('c', ['5', '6', '7', '8'])]\n?        \
    \    ++++++++++\n\n"
  killer: test2 (test__dictset.TestDictSet_update)
  module: *id001
  mutations:
  - lineno: 161
    operator: LOR
  number: 236
  status: killed
  tests_run: 172
  time: 0.018953323364257812
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 169
    operator: LOR
  number: 237
  status: survived
  tests_run: 173
  time: 0.016953706741333008
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 173, in test25\n    s2l('a1             b  123  c  45678'))\nAssertionError:\
    \ Lists differ: [('a', []), ('b', ['1', '2', '3']), ('c', ['5', '6'])] != [('a',\
    \ ['1']), ('b', ['1', '2', '3']), ('c', ['4', '5', '6', '7', '8'])]\n\nFirst differing\
    \ element 0:\n('a', [])\n('a', ['1'])\n\n- [('a', []), ('b', ['1', '2', '3']),\
    \ ('c', ['5', '6'])]\n+ [('a', ['1']), ('b', ['1', '2', '3']), ('c', ['4', '5',\
    \ '6', '7', '8'])]\n?         +++                                   +++++    \
    \   ++++++++++\n\n"
  killer: test25 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 175
    operator: LOR
  number: 238
  status: killed
  tests_run: 35
  time: 0.004982709884643555
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 219
    operator: LOR
  number: 239
  status: killed
  tests_run: 12
  time: 0.001995086669921875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 228
    operator: LOR
  number: 240
  status: killed
  tests_run: 12
  time: 0.001984119415283203
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 248
    operator: LOR
  number: 241
  status: killed
  tests_run: 65
  time: 0.00597381591796875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 257
    operator: LOR
  number: 242
  status: killed
  tests_run: 65
  time: 0.0059740543365478516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1371, in test31\n    self.assertFalse(L <= M)\nAssertionError: True is not false\n"
  killer: test31 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 273
    operator: LOR
  number: 243
  status: killed
  tests_run: 59
  time: 0.00498509407043457
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 300
    operator: LOR
  number: 244
  status: killed
  tests_run: 15
  time: 0.0019922256469726562
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 597, in test1\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test1 (test__dictset.TestDictSet__ior__)
  module: *id001
  mutations:
  - lineno: 326
    operator: LOR
  number: 245
  status: killed
  tests_run: 42
  time: 0.00399327278137207
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1240, in test2\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['5', '7', '8']), ('d', [])] != [('a', ['1']), ('c', ['5',\
    \ '7', '8'])]\n\nFirst list contains 1 additional elements.\nFirst extra element\
    \ 2:\n('d', [])\n\n- [('a', ['1']), ('c', ['5', '7', '8']), ('d', [])]\n?    \
    \                                  --------- --\n\n+ [('a', ['1']), ('c', ['5',\
    \ '7', '8'])]\n"
  killer: test2 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 361
    operator: LOR
  number: 246
  status: killed
  tests_run: 3
  time: 0.001995563507080078
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1052, in test0\n    self.assertEqual(d2l(L - M), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['5', '6', '7', '8']), ('e', [])] != [('a', ['1']), ('c',\
    \ ['5', '6', '7', '8'])]\n\nFirst list contains 1 additional elements.\nFirst\
    \ extra element 2:\n('e', [])\n\n- [('a', ['1']), ('c', ['5', '6', '7', '8']),\
    \ ('e', [])]\n?                                           --------- --\n\n+ [('a',\
    \ ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__sub__)
  module: *id001
  mutations:
  - lineno: 393
    operator: LOR
  number: 247
  status: killed
  tests_run: 75
  time: 0.0064220428466796875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 789, in test1\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test1 (test__dictset.TestDictSet__ixor__)
  module: *id001
  mutations:
  - lineno: 426
    operator: LOR
  number: 248
  status: killed
  tests_run: 53
  time: 0.0051653385162353516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 826, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('a', ['1']), ('c', ['5', '6', '7', '8'])] != []\n\nFirst list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- [('a',\
    \ ['1']), ('c', ['5', '6', '7', '8'])]\n+ []\n"
  killer: test0 (test__dictset.TestDictSet_intersection_update)
  module: *id001
  mutations:
  - lineno: 455
    operator: LOR
  number: 249
  status: killed
  tests_run: 124
  time: 0.011553287506103516
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 478
    operator: LOR
  number: 250
  status: survived
  tests_run: 173
  time: 0.01800394058227539
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 741, in test1\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test1 (test__dictset.TestDictSet_symmetric_difference_update)
  module: *id001
  mutations:
  - lineno: 502
    operator: LOR
  number: 251
  status: killed
  tests_run: 158
  time: 0.014989852905273438
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 7
    operator: ROR
  number: 252
  status: incompetent
  tests_run: 0
  time: 0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 674, in unique_combinations\nNameError: name 'reduce'\
    \ is not defined\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 9
    operator: ROR
  number: 253
  status: killed
  tests_run: 166
  time: 0.01795339584350586
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 58
    operator: ROR
  number: 254
  status: killed
  tests_run: 1
  time: 0.0009980201721191406
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 61
    operator: ROR
  number: 255
  status: killed
  tests_run: 1
  time: 0.0009963512420654297
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 131, in test6\n    DictSet([(set('one'), [1]), ('two', [2])], {'three': [3]})\n\
    AssertionError: TypeError not raised\n"
  killer: test6 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 64
    operator: ROR
  number: 256
  status: killed
  tests_run: 39
  time: 0.003989219665527344
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 64
    operator: ROR
  number: 257
  status: survived
  tests_run: 173
  time: 0.019946575164794922
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 89
    operator: ROR
  number: 258
  status: survived
  tests_run: 173
  time: 0.01623821258544922
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 89
    operator: ROR
  number: 259
  status: incompetent
  tests_run: 1
  time: 0.0009615421295166016
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: too many\
    \ values to unpack (expected 2)\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 95
    operator: ROR
  number: 260
  status: killed
  tests_run: 36
  time: 0.004987239837646484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 110, in test3\n    DictSet(['one', [1], 'two', [2]])\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 166, in update\nValueError: too many\
    \ values to unpack (expected 2)\n"
  killer: test3 (test__dictset.TestDictSet__init__)
  module: *id001
  mutations:
  - lineno: 100
    operator: ROR
  number: 261
  status: killed
  tests_run: 36
  time: 0.005021095275878906
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1221, in test0\n    self.assertEqual(d2l(L), s2l('a1 c5678'))\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 153
    operator: ROR
  number: 262
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 219
    operator: ROR
  number: 263
  status: killed
  tests_run: 12
  time: 0.0019600391387939453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 220
    operator: ROR
  number: 264
  status: killed
  tests_run: 12
  time: 0.0020341873168945312
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 219
    operator: ROR
  number: 265
  status: survived
  tests_run: 173
  time: 0.01990222930908203
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 219
    operator: ROR
  number: 266
  status: killed
  tests_run: 12
  time: 0.0024871826171875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1271, in test3\n    self.assertTrue(L.__eq__(M))\nAssertionError: False is not\
    \ true\n"
  killer: test3 (test__dictset.TestDictSet__eq__)
  module: *id001
  mutations:
  - lineno: 229
    operator: ROR
  number: 267
  status: killed
  tests_run: 12
  time: 0.0019490718841552734
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 248
    operator: ROR
  number: 268
  status: killed
  tests_run: 65
  time: 0.00598454475402832
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 249
    operator: ROR
  number: 269
  status: killed
  tests_run: 65
  time: 0.007002353668212891
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 248
    operator: ROR
  number: 270
  status: survived
  tests_run: 173
  time: 0.020899057388305664
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 248
    operator: ROR
  number: 271
  status: killed
  tests_run: 65
  time: 0.00598597526550293
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1298, in test3\n    self.assertFalse(L.__ne__(M))\nAssertionError: True is not\
    \ false\n"
  killer: test3 (test__dictset.TestDictSet__ne__)
  module: *id001
  mutations:
  - lineno: 258
    operator: ROR
  number: 272
  status: killed
  tests_run: 65
  time: 0.0060198307037353516
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 269
    operator: ROR
  number: 273
  status: survived
  tests_run: 173
  time: 0.016965866088867188
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 269
    operator: ROR
  number: 274
  status: survived
  tests_run: 173
  time: 0.016995906829833984
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1354, in test0\n    self.assertTrue(L <= M)\nAssertionError: False is not true\n"
  killer: test0 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 274
    operator: ROR
  number: 275
  status: killed
  tests_run: 56
  time: 0.004979610443115234
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1366, in test3\n    self.assertTrue(L <= M)\nAssertionError: False is not true\n"
  killer: test3 (test__dictset.TestDictSet__le__)
  module: *id001
  mutations:
  - lineno: 274
    operator: ROR
  number: 276
  status: killed
  tests_run: 58
  time: 0.004976749420166016
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 296
    operator: ROR
  number: 277
  status: survived
  tests_run: 173
  time: 0.018038272857666016
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 296
    operator: ROR
  number: 278
  status: survived
  tests_run: 173
  time: 0.017032623291015625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 301
    operator: ROR
  number: 279
  status: killed
  tests_run: 15
  time: 0.0014004707336425781
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1449, in test31\n    self.assertTrue(L >= M)\nAssertionError: False is not true\n"
  killer: test31 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 301
    operator: ROR
  number: 280
  status: killed
  tests_run: 18
  time: 0.002029895782470703
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1240, in test2\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [] != [('a', ['1']), ('c', ['5', '7', '8'])]\n\nSecond list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n+ [('a', ['1']), ('c',\
    \ ['5', '7', '8'])]\n"
  killer: test2 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 357
    operator: ROR
  number: 281
  status: killed
  tests_run: 3
  time: 0.0009510517120361328
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 826, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [('a', []), ('c', [])] != []\n\nFirst list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', [])\n\n- [('a', []), ('c', [])]\n+\
    \ []\n"
  killer: test0 (test__dictset.TestDictSet_intersection_update)
  module: *id001
  mutations:
  - lineno: 458
    operator: ROR
  number: 282
  status: killed
  tests_run: 124
  time: 0.014914989471435547
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 634, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet_difference_update)
  module: *id001
  mutations:
  - lineno: 481
    operator: ROR
  number: 283
  status: killed
  tests_run: 100
  time: 0.01097559928894043
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 730, in test0\n    self.assertEqual(d2l(L), R)  # L is updated\nAssertionError:\
    \ Lists differ: [] != [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\nSecond list\
    \ contains 2 additional elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n"
  killer: test0 (test__dictset.TestDictSet_symmetric_difference_update)
  module: *id001
  mutations:
  - lineno: 505
    operator: ROR
  number: 284
  status: killed
  tests_run: 157
  time: 0.014995574951171875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 282, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1']), ('c', ['5', '6', '7', '8'])] != [('a', ['1']), ('c', ['5', '6',\
    \ '7', '8', '9'])]\n\nFirst differing element 1:\n('c', ['5', '6', '7', '8'])\n\
    ('c', ['5', '6', '7', '8', '9'])\n\n- [('a', ['1']), ('c', ['5', '6', '7', '8'])]\n\
    + [('a', ['1']), ('c', ['5', '6', '7', '8', '9'])]\n?                        \
    \                +++++\n\n"
  killer: test0 (test__dictset.TestDictSet_add)
  module: *id001
  mutations:
  - lineno: 529
    operator: ROR
  number: 285
  status: killed
  tests_run: 83
  time: 0.008975028991699219
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1240, in test2\n    self.assertEqual(d2l(L & M), R)\nAssertionError: Lists differ:\
    \ [] != [('a', ['1']), ('c', ['5', '7', '8'])]\n\nSecond list contains 2 additional\
    \ elements.\nFirst extra element 0:\n('a', ['1'])\n\n- []\n+ [('a', ['1']), ('c',\
    \ ['5', '7', '8'])]\n"
  killer: test2 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 549
    operator: ROR
  number: 286
  status: killed
  tests_run: 3
  time: 0.0002906322479248047
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1482, in test3\n    self.assertFalse('d' in L)  # d is a key, but has an empty\
    \ set\nAssertionError: True is not false\n"
  killer: test3 (test__dictset.TestDictSet__contains__)
  module: *id001
  mutations:
  - lineno: 549
    operator: ROR
  number: 287
  status: killed
  tests_run: 8
  time: 0.001995086669921875
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1432, in test0\n    self.assertFalse(L >= M)\nAssertionError: True is not false\n"
  killer: test0 (test__dictset.TestDictSet__ge__)
  module: *id001
  mutations:
  - lineno: 558
    operator: ROR
  number: 288
  status: killed
  tests_run: 15
  time: 0.0019855499267578125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1528, in test1\n    self.assertEqual(set([v for v in g]) ^ set('abc'), set())\n\
    AssertionError: Items in the first set but not the second:\n'd'\n"
  killer: test1 (test__dictset.TestDictSet__iter__)
  module: *id001
  mutations:
  - lineno: 558
    operator: ROR
  number: 289
  status: killed
  tests_run: 50
  time: 0.0049402713775634766
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 568
    operator: ROR
  number: 290
  status: incompetent
  tests_run: 78
  time: 0.011920928955078125
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1229, in test1\n    self.assertTrue(isinstance(L & M, DictSet))\n  File \"dictset\"\
    , line 378, in __and__\n  File \"dictset\", line 363, in intersection\nKeyError:\
    \ 'd'\n"
  killer: test1 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 584
    operator: ROR
  number: 291
  status: killed
  tests_run: 2
  time: 0.0019478797912597656
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 341, in test01\n    L.remove('c')\n  File \"dictset\", line 609, in remove\n\
    KeyError: None\n"
  killer: test01 (test__dictset.TestDictSet_copy)
  module: *id001
  mutations:
  - lineno: 608
    operator: ROR
  number: 292
  status: killed
  tests_run: 92
  time: 0.009874343872070312
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 389, in test0\n    self.assertEqual(d2l(L), R)\nAssertionError: Lists differ:\
    \ [('a', ['1'])] != [('a', ['1']), ('c', ['5', '6', '7'])]\n\nSecond list contains\
    \ 1 additional elements.\nFirst extra element 1:\n('c', ['5', '6', '7'])\n\n-\
    \ [('a', ['1'])]\n+ [('a', ['1']), ('c', ['5', '6', '7'])]\n"
  killer: test0 (test__dictset.TestDictSet_discard)
  module: *id001
  mutations:
  - lineno: 622
    operator: ROR
  number: 293
  status: killed
  tests_run: 104
  time: 0.011009693145751953
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1544, in test0\n    self.assertEqual([v for v in g], [None])\nAssertionError:\
    \ Lists differ: [['1', '5'], ['1', '6'], ['1', '7'], ['1', '8']] != [None]\n\n\
    First differing element 0:\n['1', '5']\nNone\n\nFirst list contains 3 additional\
    \ elements.\nFirst extra element 1:\n['1', '6']\n\n- [['1', '5'], ['1', '6'],\
    \ ['1', '7'], ['1', '8']]\n+ [None]\n"
  killer: test0 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 657
    operator: ROR
  number: 294
  status: killed
  tests_run: 165
  time: 0.015951871871948242
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 668
    operator: ROR
  number: 295
  status: incompetent
  tests_run: 165
  time: 0.014951705932617188
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1550, in test1\n    self.assertEqual([v for v in g], [['1', '5'],\n  File \"\
    C:\\Users\\steph\\Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\"\
    , line 1550, in <listcomp>\n    self.assertEqual([v for v in g], [['1', '5'],\n\
    \  File \"dictset\", line 687, in unique_combinations\nZeroDivisionError: division\
    \ by zero\n"
  killer: test1 (test__dictset.TestDictSet_unique_combinations)
  module: *id001
  mutations:
  - lineno: 685
    operator: ROR
  number: 296
  status: killed
  tests_run: 166
  time: 0.02089858055114746
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 706
    operator: ROR
  number: 297
  status: incompetent
  tests_run: 113
  time: 0.010960102081298828
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 52, in __init__\nRuntimeError: super(): no arguments\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 37
    operator: SCI
  number: 298
  status: killed
  tests_run: 1
  time: 0.00199127197265625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\steph\\\
    Desktop\\Thesis\\Feature Scripts\\Working\\src\\tests\\test__dictset.py\", line\
    \ 1215, in test0\n    L = DictSet(s2d('a1 c5666788'))\n  File \"dictset\", line\
    \ 62, in __init__\n  File \"dictset\", line 87, in update\nRuntimeError: super():\
    \ no arguments\n"
  killer: test0 (test__dictset.TestDictSet__and__)
  module: *id001
  mutations:
  - lineno: 68
    operator: SCI
  number: 299
  status: killed
  tests_run: 1
  time: 0.0019943714141845703
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 202
    operator: SCI
  number: 300
  status: survived
  tests_run: 173
  time: 0.015910625457763672
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 231
    operator: SCI
  number: 301
  status: survived
  tests_run: 173
  time: 0.01699352264404297
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 279
    operator: SCI
  number: 302
  status: survived
  tests_run: 173
  time: 0.016043663024902344
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 306
    operator: SCI
  number: 303
  status: survived
  tests_run: 173
  time: 0.015948057174682617
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 532
    operator: SCI
  number: 304
  status: survived
  tests_run: 173
  time: 0.01597142219543457
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 542
    operator: SCI
  number: 305
  status: incompetent
  tests_run: 172
  time: 0.01695561408996582
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 551
    operator: SCI
  number: 306
  status: survived
  tests_run: 173
  time: 0.021899938583374023
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 561
    operator: SCI
  number: 307
  status: incompetent
  tests_run: 87
  time: 0.014001846313476562
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 576
    operator: SCI
  number: 308
  status: incompetent
  tests_run: 112
  time: 0.014053821563720703
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 593
    operator: SCI
  number: 309
  status: survived
  tests_run: 173
  time: 0.017400741577148438
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 635
    operator: SCI
  number: 310
  status: survived
  tests_run: 173
  time: 0.0170748233795166
- exception_traceback: null
  killer: null
  module: *id001
  mutations:
  - lineno: 697
    operator: SCI
  number: 311
  status: incompetent
  tests_run: 113
  time: 0.010922908782958984
number_of_tests: 173
targets:
- src/dictset.py
tests:
- name: test__dictset
  target: null
  time: 0.019487857818603516
time_stats:
  create_mutant_module: 0.587071418762207
  create_target_ast: 0.015956878662109375
  mutate_module: 6.048203468322754
  run_tests_with_mutant: 3.839172840118408
total_time: 6.072678089141846
